export const marketplaceErrorCodeValues = [
  "ATTESTATION_EXPIRED",
  "ATTESTATION_EXPIRY_INVALID",
  "ATTESTATION_INPUT_INVALID",
  "ATTESTATION_JSON_INVALID",
  "ATTESTATION_KEY_MISMATCH",
  "ATTESTATION_MANDATE_HASH_MISMATCH",
  "ATTESTATION_NONCANONICAL",
  "ATTESTATION_NOT_YET_VALID",
  "ATTESTATION_OBSERVATION_AFTER_ISSUANCE",
  "ATTESTATION_PAYLOAD_HASH_MISMATCH",
  "ATTESTATION_POLICY_MISMATCH",
  "ATTESTATION_SCHEMA_INVALID",
  "ATTESTATION_SIGNATURE_INVALID",
  "ATTESTATION_TOO_LARGE",
  "ATTESTATION_TRUST_INVALID",
  "ATTESTATION_TTL_EXCEEDED",
  "ATTESTATION_UTF8_INVALID",
  "CANDIDATE_SET_INVALID",
  "CANDIDATE_LIMIT_EXCEEDED",
  "CORE_CLOCK_INVALID",
  "DISPLAY_SAFE_PROJECTION_NOT_CAPTURED_BY_CORE",
  "DUPLICATE_CANDIDATE",
  "DUPLICATE_QUOTE_ID",
  "EVALUATION_INPUT_INVALID",
  "EVALUATED_AT_BEFORE_MANDATE",
  "EVALUATED_AT_INVALID",
  "INTEGRITY_DECISIONS_INVALID",
  "INTEGRITY_MANDATE_INVALID",
  "INTEGRITY_NONCANONICAL_INPUT",
  "INTEGRITY_RECEIPT_INVALID",
  "INTEGRITY_RESULT_SHAPE_INVALID",
  "INTEGRITY_RESULT_TOO_LARGE",
  "INTEGRITY_RESULT_UNORDERED",
  "INTEGRITY_UNIQUENESS_INVALID",
  "INTEGRITY_QUOTES_INVALID",
  "MANDATE_INVALID",
  "TRUSTED_INGRESS_INSTALLER_INVALID",
  "TRUSTED_PROJECTION_INVALID",
] as const;
export type MarketplaceErrorCode = (typeof marketplaceErrorCodeValues)[number];

export class MarketplaceCoreError extends Error {
  readonly code: MarketplaceErrorCode;

  constructor(code: MarketplaceErrorCode, message: string, options?: ErrorOptions) {
    super(message, options);
    this.name = "MarketplaceCoreError";
    this.code = code;
  }
}
